In [4]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from scikit-learn) (2.1.0)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 1.9 MB/s eta 0:00:05
   --- ------------------------------------ 0.8/8.0 MB 2.0 MB/s eta 0:00:04
   ------ --------------------------------- 1.3/8.0 MB 1.9 MB/s eta 0:00:04
   --------- ------------------------------ 1.8/8.0 MB 1.9 MB/s eta 0:00:04
   ---------- ----------------------------- 2.1/8.0 MB 1.9 MB/s eta 0:00:04
   ------------- -------------------------- 2.6/8.0 MB 1.8 MB/s eta 0:00:03
   -------------- ------------------------- 2.9/8.0 MB 1.9 MB/s eta 0:00:03
   ---------------- ----------------------- 3.4/8.0 MB 1.8 MB/s eta 0:00:03
   ------------------- -------------------- 3.9/8.0 MB 1.8 MB/s eta 0:00:03
   -------------------- ------------------- 4.2/8.0 MB 1.8 MB/s eta 0:00:03
   ----------------------- ---------------- 4.7/8.0 MB 1.8 MB/s eta 0:00:02
   ------------------------ --------------- 5.0/8.0 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.0 MB 1.8 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.0 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 6.3/8.0 MB 1.8 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.0 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.0 MB 1.8 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.0 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 1.8 MB/s eta 0:00:00
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.5 MB ? eta -:--:--
    --------------------------------------- 0.8/36.5 MB 2.1 MB/s eta 0:00:18
   - -------------------------------------- 1.3/36.5 MB 2.0 MB/s eta 0:00:18
   - -------------------------------------- 1.6/36.5 MB 1.9 MB/s eta 0:00:19
   -- ------------------------------------- 2.1/36.5 MB 1.9 MB/s eta 0:00:19
   -- ------------------------------------- 2.6/36.5 MB 1.9 MB/s eta 0:00:18
   --- ------------------------------------ 2.9/36.5 MB 1.8 MB/s eta 0:00:19
   --- ------------------------------------ 3.1/36.5 MB 1.8 MB/s eta 0:00:19
   ---- ----------------------------------- 3.7/36.5 MB 1.8 MB/s eta 0:00:19
   ---- ----------------------------------- 3.9/36.5 MB 1.8 MB/s eta 0:00:18
   ---- ----------------------------------- 4.5/36.5 MB 1.8 MB/s eta 0:00:18
   ----- ---------------------------------- 4.7/36.5 MB 1.8 MB/s eta 0:00:18
   ----- ---------------------------------- 5.2/36.5 MB 1.8 MB/s eta 0:00:18
   ------ --------------------------------- 5.8/36.5 MB 1.8 MB/s eta 0:00:17
   ------ --------------------------------- 6.0/36.5 MB 1.8 MB/s eta 0:00:17
   ------- -------------------------------- 6.6/36.5 MB 1.8 MB/s eta 0:00:17
   ------- -------------------------------- 6.8/36.5 MB 1.8 MB/s eta 0:00:17
   -------- ------------------------------- 7.3/36.5 MB 1.8 MB/s eta 0:00:17
   -------- ------------------------------- 7.6/36.5 MB 1.8 MB/s eta 0:00:16
   -------- ------------------------------- 8.1/36.5 MB 1.8 MB/s eta 0:00:16
   --------- ------------------------------ 8.4/36.5 MB 1.8 MB/s eta 0:00:16
   --------- ------------------------------ 8.9/36.5 MB 1.8 MB/s eta 0:00:16
   ---------- ----------------------------- 9.4/36.5 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 9.7/36.5 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 10.0/36.5 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 10.0/36.5 MB 1.8 MB/s eta 0:00:15
   ----------- ---------------------------- 10.5/36.5 MB 1.7 MB/s eta 0:00:16
   ------------ --------------------------- 11.0/36.5 MB 1.8 MB/s eta 0:00:15
   ------------ --------------------------- 11.5/36.5 MB 1.8 MB/s eta 0:00:15
   ------------- -------------------------- 12.1/36.5 MB 1.8 MB/s eta 0:00:14
   ------------- -------------------------- 12.3/36.5 MB 1.8 MB/s eta 0:00:14
   ------------- -------------------------- 12.6/36.5 MB 1.8 MB/s eta 0:00:14
   -------------- ------------------------- 13.1/36.5 MB 1.8 MB/s eta 0:00:14
   -------------- ------------------------- 13.1/36.5 MB 1.8 MB/s eta 0:00:14
   -------------- ------------------------- 13.4/36.5 MB 1.7 MB/s eta 0:00:14
   -------------- ------------------------- 13.6/36.5 MB 1.7 MB/s eta 0:00:14
   --------------- ------------------------ 14.2/36.5 MB 1.7 MB/s eta 0:00:14
   --------------- ------------------------ 14.4/36.5 MB 1.7 MB/s eta 0:00:14
   ---------------- ----------------------- 14.9/36.5 MB 1.7 MB/s eta 0:00:13
   ---------------- ----------------------- 15.2/36.5 MB 1.7 MB/s eta 0:00:13
   ----------------- ---------------------- 15.7/36.5 MB 1.7 MB/s eta 0:00:13
   ----------------- ---------------------- 16.0/36.5 MB 1.7 MB/s eta 0:00:13
   ------------------ --------------------- 16.5/36.5 MB 1.7 MB/s eta 0:00:12
   ------------------ --------------------- 17.0/36.5 MB 1.7 MB/s eta 0:00:12
   ------------------ --------------------- 17.3/36.5 MB 1.7 MB/s eta 0:00:12
   ------------------- -------------------- 17.6/36.5 MB 1.7 MB/s eta 0:00:12
   ------------------- -------------------- 18.1/36.5 MB 1.7 MB/s eta 0:00:11
   -------------------- ------------------- 18.4/36.5 MB 1.7 MB/s eta 0:00:11
   -------------------- ------------------- 18.9/36.5 MB 1.7 MB/s eta 0:00:11
   -------------------- ------------------- 18.9/36.5 MB 1.7 MB/s eta 0:00:11
   -------------------- ------------------- 18.9/36.5 MB 1.7 MB/s eta 0:00:11
   -------------------- ------------------- 19.1/36.5 MB 1.6 MB/s eta 0:00:11
   --------------------- ------------------ 19.4/36.5 MB 1.6 MB/s eta 0:00:11
   --------------------- ------------------ 19.9/36.5 MB 1.6 MB/s eta 0:00:11
   ---------------------- ----------------- 20.2/36.5 MB 1.6 MB/s eta 0:00:10
   ---------------------- ----------------- 20.7/36.5 MB 1.6 MB/s eta 0:00:10
   ---------------------- ----------------- 21.0/36.5 MB 1.7 MB/s eta 0:00:10
   ----------------------- ---------------- 21.2/36.5 MB 1.7 MB/s eta 0:00:10
   ----------------------- ---------------- 21.2/36.5 MB 1.7 MB/s eta 0:00:10
   ------------------------ --------------- 22.0/36.5 MB 1.6 MB/s eta 0:00:09
   ------------------------ --------------- 22.3/36.5 MB 1.6 MB/s eta 0:00:09
   ------------------------ --------------- 22.8/36.5 MB 1.6 MB/s eta 0:00:09
   ------------------------- -------------- 23.1/36.5 MB 1.6 MB/s eta 0:00:09
   ------------------------- -------------- 23.3/36.5 MB 1.6 MB/s eta 0:00:09
   -------------------------- ------------- 23.9/36.5 MB 1.6 MB/s eta 0:00:08
   -------------------------- ------------- 24.1/36.5 MB 1.6 MB/s eta 0:00:08
   -------------------------- ------------- 24.1/36.5 MB 1.6 MB/s eta 0:00:08
   -------------------------- ------------- 24.1/36.5 MB 1.6 MB/s eta 0:00:08
   -------------------------- ------------- 24.6/36.5 MB 1.6 MB/s eta 0:00:08
   --------------------------- ------------ 25.2/36.5 MB 1.6 MB/s eta 0:00:08
   --------------------------- ------------ 25.4/36.5 MB 1.6 MB/s eta 0:00:07
   ---------------------------- ----------- 26.0/36.5 MB 1.6 MB/s eta 0:00:07
   ---------------------------- ----------- 26.5/36.5 MB 1.6 MB/s eta 0:00:07
   ----------------------------- ---------- 26.7/36.5 MB 1.6 MB/s eta 0:00:07
   ----------------------------- ---------- 27.0/36.5 MB 1.6 MB/s eta 0:00:06
   ----------------------------- ---------- 27.0/36.5 MB 1.6 MB/s eta 0:00:06
   ----------------------------- ---------- 27.3/36.5 MB 1.6 MB/s eta 0:00:06
   ------------------------------ --------- 27.8/36.5 MB 1.6 MB/s eta 0:00:06
   ------------------------------ --------- 28.3/36.5 MB 1.6 MB/s eta 0:00:06
   ------------------------------- -------- 28.6/36.5 MB 1.6 MB/s eta 0:00:06
   ------------------------------- -------- 28.8/36.5 MB 1.6 MB/s eta 0:00:05
   -------------------------------- ------- 29.6/36.5 MB 1.6 MB/s eta 0:00:05
   -------------------------------- ------- 29.9/36.5 MB 1.6 MB/s eta 0:00:05
   -------------------------------- ------- 30.1/36.5 MB 1.6 MB/s eta 0:00:04
   -------------------------------- ------- 30.1/36.5 MB 1.6 MB/s eta 0:00:04
   --------------------------------- ------ 30.4/36.5 MB 1.6 MB/s eta 0:00:04
   --------------------------------- ------ 30.9/36.5 MB 1.6 MB/s eta 0:00:04
   ---------------------------------- ----- 31.2/36.5 MB 1.6 MB/s eta 0:00:04
   ---------------------------------- ----- 31.7/36.5 MB 1.6 MB/s eta 0:00:04
   ----------------------------------- ---- 32.0/36.5 MB 1.6 MB/s eta 0:00:03
   ----------------------------------- ---- 32.5/36.5 MB 1.6 MB/s eta 0:00:03
   ----------------------------------- ---- 32.8/36.5 MB 1.6 MB/s eta 0:00:03
   ------------------------------------ --- 33.0/36.5 MB 1.6 MB/s eta 0:00:03
   ------------------------------------ --- 33.0/36.5 MB 1.6 MB/s eta 0:00:03
   ------------------------------------ --- 33.3/36.5 MB 1.6 MB/s eta 0:00:03
   ------------------------------------- -- 33.8/36.5 MB 1.6 MB/s eta 0:00:02
   ------------------------------------- -- 34.3/36.5 MB 1.6 MB/s eta 0:00:02
   ------------------------------------- -- 34.6/36.5 MB 1.6 MB/s eta 0:00:02
   -------------------------------------- - 35.1/36.5 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  35.9/36.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  35.9/36.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 1.5 MB/s eta 0:00:00
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
# Modelling
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [6]:
pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\admin\appdata\roaming\python\python312\site-packages (from catboost) (3.9.2)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from catboost) (2.1.0)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\admin\appdata\roaming\python\python312\site-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in e:\college material\python\venv\lib\site-packages (from catboost) (1.17.1)
Collecting plotly (from catboost)
  Downloading plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: six in c:\users\admin\appdata\roaming\python\python312\site-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pandas<4.0,>=0.24->catboost) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pandas<4.0,>=0.24->catboost) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\admin\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from matplotlib->catboost) (3.1.2)
Collecting narwhals>=1.15.1 (from plotly->catboost)
  Downloading narwhals-2.20.0-py3-none-any.whl.metadata (15 kB)
Downloading catboost-1.2.10-cp312-cp312-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.5/100.2 MB 202.1 kB/s eta 0:08:14
   ---------------------------------------- 0.8/100.2 MB 325.6 kB/s eta 0:05:06
   ---------------------------------------- 0.8/100.2 MB 325.6 kB/s eta 0:05:06
   ---------------------------------------- 0.8/100.2 MB 325.6 kB/s eta 0:05:06
   ---------------------------------------- 1.0/100.2 MB 364.8 kB/s eta 0:04:32
   ---------------------------------------- 1.0/100.2 MB 364.8 kB/s eta 0:04:32
   ---------------------------------------- 1.0/100.2 MB 364.8 kB/s eta 0:04:32
   ---------------------------------------- 1.0/100.2 MB 364.8 kB/s eta 0:04:32
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.3/100.2 MB 335.5 kB/s eta 0:04:55
    --------------------------------------- 1.6/100.2 MB 202.1 kB/s eta 0:08:09
    --------------------------------------- 1.6/100.2 MB 202.1 kB/s eta 0:08:09
    --------------------------------------- 1.6/100.2 MB 202.1 kB/s eta 0:08:09
    --------------------------------------- 1.6/100.2 MB 202.1 kB/s eta 0:08:09
    --------------------------------------- 1.6/100.2 MB 202.1 kB/s eta 0:08:09
    --------------------------------------- 1.6/100.2 MB 202.1 kB/s eta 0:08:09
    --------------------------------------- 1.6/100.2 MB 202.1 kB/s eta 0:08:09
    --------------------------------------- 1.6/100.2 MB 202.1 kB/s eta 0:08:09
    --------------------------------------- 1.8/100.2 MB 188.5 kB/s eta 0:08:42
    --------------------------------------- 1.8/100.2 MB 188.5 kB/s eta 0:08:42
    --------------------------------------- 1.8/100.2 MB 188.5 kB/s eta 0:08:42
    --------------------------------------- 2.1/100.2 MB 206.8 kB/s eta 0:07:55
    --------------------------------------- 2.4/100.2 MB 226.7 kB/s eta 0:07:12
    --------------------------------------- 2.4/100.2 MB 226.7 kB/s eta 0:07:12
   - -------------------------------------- 2.6/100.2 MB 242.8 kB/s eta 0:06:43
   - -------------------------------------- 2.6/100.2 MB 242.8 kB/s eta 0:06:43
   - -------------------------------------- 2.9/100.2 MB 260.1 kB/s eta 0:06:15
   - -------------------------------------- 2.9/100.2 MB 260.1 kB/s eta 0:06:15
   - -------------------------------------- 3.1/100.2 MB 273.4 kB/s eta 0:05:56
   - -------------------------------------- 3.1/100.2 MB 273.4 kB/s eta 0:05:56
   - -------------------------------------- 3.1/100.2 MB 273.4 kB/s eta 0:05:56
   - -------------------------------------- 3.1/100.2 MB 273.4 kB/s eta 0:05:56
   - -------------------------------------- 3.4/100.2 MB 275.4 kB/s eta 0:05:52
   - -------------------------------------- 3.4/100.2 MB 275.4 kB/s eta 0:05:52
   - -------------------------------------- 3.4/100.2 MB 275.4 kB/s eta 0:05:52
   - -------------------------------------- 3.4/100.2 MB 275.4 kB/s eta 0:05:52
   - -------------------------------------- 3.4/100.2 MB 275.4 kB/s eta 0:05:52
   - -------------------------------------- 3.4/100.2 MB 275.4 kB/s eta 0:05:52
   - -------------------------------------- 3.4/100.2 MB 275.4 kB/s eta 0:05:52
   - -------------------------------------- 3.7/100.2 MB 262.1 kB/s eta 0:06:09
   - -------------------------------------- 3.7/100.2 MB 262.1 kB/s eta 0:06:09
   - -------------------------------------- 3.9/100.2 MB 274.4 kB/s eta 0:05:51
   - -------------------------------------- 4.2/100.2 MB 288.6 kB/s eta 0:05:33
   - -------------------------------------- 4.5/100.2 MB 304.0 kB/s eta 0:05:15
   - -------------------------------------- 4.7/100.2 MB 315.5 kB/s eta 0:05:03
   - -------------------------------------- 4.7/100.2 MB 315.5 kB/s eta 0:05:03
   - -------------------------------------- 5.0/100.2 MB 324.7 kB/s eta 0:04:54
   -- ------------------------------------- 5.2/100.2 MB 337.0 kB/s eta 0:04:42
   -- ------------------------------------- 5.2/100.2 MB 337.0 kB/s eta 0:04:42
   -- ------------------------------------- 5.5/100.2 MB 346.3 kB/s eta 0:04:34
   -- ------------------------------------- 5.8/100.2 MB 354.1 kB/s eta 0:04:27
   -- ------------------------------------- 5.8/100.2 MB 354.1 kB/s eta 0:04:27
   -- ------------------------------------- 6.0/100.2 MB 361.1 kB/s eta 0:04:21
   -- ------------------------------------- 6.0/100.2 MB 361.1 kB/s eta 0:04:21
   -- ------------------------------------- 6.6/100.2 MB 383.5 kB/s eta 0:04:05
   -- ------------------------------------- 6.8/100.2 MB 394.2 kB/s eta 0:03:57
   -- ------------------------------------- 7.1/100.2 MB 405.0 kB/s eta 0:03:50
   -- ------------------------------------- 7.3/100.2 MB 414.4 kB/s eta 0:03:45
   --- ------------------------------------ 7.6/100.2 MB 422.8 kB/s eta 0:03:40
   --- ------------------------------------ 7.9/100.2 MB 433.2 kB/s eta 0:03:34
   --- ------------------------------------ 8.1/100.2 MB 445.0 kB/s eta 0:03:27
   --- ------------------------------------ 8.4/100.2 MB 452.2 kB/s eta 0:03:24
   --- ------------------------------------ 8.7/100.2 MB 460.4 kB/s eta 0:03:19
   --- ------------------------------------ 9.2/100.2 MB 482.6 kB/s eta 0:03:09
   --- ------------------------------------ 9.4/100.2 MB 492.6 kB/s eta 0:03:05
   --- ----------------------------------- 10.0/100.2 MB 512.6 kB/s eta 0:02:57
   --- ----------------------------------- 10.0/100.2 MB 512.6 kB/s eta 0:02:57
   ---- ---------------------------------- 10.5/100.2 MB 527.7 kB/s eta 0:02:51
   ---- ---------------------------------- 10.7/100.2 MB 536.4 kB/s eta 0:02:47
   ---- ---------------------------------- 11.0/100.2 MB 545.5 kB/s eta 0:02:44
   ---- ---------------------------------- 11.0/100.2 MB 545.5 kB/s eta 0:02:44
   ---- ---------------------------------- 11.0/100.2 MB 545.5 kB/s eta 0:02:44
   ---- ---------------------------------- 11.3/100.2 MB 539.5 kB/s eta 0:02:45
   ---- ---------------------------------- 11.5/100.2 MB 543.6 kB/s eta 0:02:44
   ---- ---------------------------------- 11.5/100.2 MB 543.6 kB/s eta 0:02:44
   ---- ---------------------------------- 11.8/100.2 MB 548.0 kB/s eta 0:02:42
   ---- ---------------------------------- 11.8/100.2 MB 548.0 kB/s eta 0:02:42
   ---- ---------------------------------- 12.1/100.2 MB 549.1 kB/s eta 0:02:41
   ---- ---------------------------------- 12.3/100.2 MB 554.0 kB/s eta 0:02:39
   ---- ---------------------------------- 12.6/100.2 MB 560.8 kB/s eta 0:02:37
   ---- ---------------------------------- 12.8/100.2 MB 566.3 kB/s eta 0:02:35
   ----- --------------------------------- 13.1/100.2 MB 570.9 kB/s eta 0:02:33
   ----- --------------------------------- 13.4/100.2 MB 578.5 kB/s eta 0:02:31
   ----- --------------------------------- 13.9/100.2 MB 590.7 kB/s eta 0:02:27
   ----- --------------------------------- 14.2/100.2 MB 598.0 kB/s eta 0:02:24
   ----- --------------------------------- 14.2/100.2 MB 598.0 kB/s eta 0:02:24
   ----- --------------------------------- 14.4/100.2 MB 599.2 kB/s eta 0:02:24
   ----- --------------------------------- 14.7/100.2 MB 604.3 kB/s eta 0:02:22
   ----- --------------------------------- 15.2/100.2 MB 618.2 kB/s eta 0:02:18
   ------ -------------------------------- 15.7/100.2 MB 633.7 kB/s eta 0:02:14
   ------ -------------------------------- 16.0/100.2 MB 639.5 kB/s eta 0:02:12
   ------ -------------------------------- 16.5/100.2 MB 654.2 kB/s eta 0:02:08
   ------ -------------------------------- 17.0/100.2 MB 668.1 kB/s eta 0:02:05
   ------ -------------------------------- 17.3/100.2 MB 674.4 kB/s eta 0:02:03
   ------ -------------------------------- 17.8/100.2 MB 687.5 kB/s eta 0:02:00
   ------- ------------------------------- 18.4/100.2 MB 700.3 kB/s eta 0:01:57
   ------- ------------------------------- 18.6/100.2 MB 706.2 kB/s eta 0:01:56
   ------- ------------------------------- 19.1/100.2 MB 718.6 kB/s eta 0:01:53
   ------- ------------------------------- 19.4/100.2 MB 724.3 kB/s eta 0:01:52
   ------- ------------------------------- 19.9/100.2 MB 735.8 kB/s eta 0:01:50
   ------- ------------------------------- 20.2/100.2 MB 740.5 kB/s eta 0:01:49
   -------- ------------------------------ 20.7/100.2 MB 752.1 kB/s eta 0:01:46
   -------- ------------------------------ 21.0/100.2 MB 757.4 kB/s eta 0:01:45
   -------- ------------------------------ 21.5/100.2 MB 769.9 kB/s eta 0:01:43
   -------- ------------------------------ 21.8/100.2 MB 774.2 kB/s eta 0:01:42
   -------- ------------------------------ 21.8/100.2 MB 774.2 kB/s eta 0:01:42
   -------- ------------------------------ 22.0/100.2 MB 772.3 kB/s eta 0:01:42
   -------- ------------------------------ 22.0/100.2 MB 772.3 kB/s eta 0:01:42
   -------- ------------------------------ 22.3/100.2 MB 768.0 kB/s eta 0:01:42
   -------- ------------------------------ 22.3/100.2 MB 768.0 kB/s eta 0:01:42
   -------- ------------------------------ 22.5/100.2 MB 764.6 kB/s eta 0:01:42
   -------- ------------------------------ 22.5/100.2 MB 764.6 kB/s eta 0:01:42
   -------- ------------------------------ 22.5/100.2 MB 764.6 kB/s eta 0:01:42
   -------- ------------------------------ 22.5/100.2 MB 764.6 kB/s eta 0:01:42
   -------- ------------------------------ 22.5/100.2 MB 764.6 kB/s eta 0:01:42
   -------- ------------------------------ 22.8/100.2 MB 768.8 kB/s eta 0:01:41
   -------- ------------------------------ 22.8/100.2 MB 768.8 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   -------- ------------------------------ 23.1/100.2 MB 765.0 kB/s eta 0:01:41
   --------- ----------------------------- 23.6/100.2 MB 783.8 kB/s eta 0:01:38
   --------- ----------------------------- 24.1/100.2 MB 795.0 kB/s eta 0:01:36
   --------- ----------------------------- 24.4/100.2 MB 800.2 kB/s eta 0:01:35
   --------- ----------------------------- 24.9/100.2 MB 810.2 kB/s eta 0:01:33
   --------- ----------------------------- 25.2/100.2 MB 815.3 kB/s eta 0:01:33
   --------- ----------------------------- 25.7/100.2 MB 825.4 kB/s eta 0:01:31
   --------- ----------------------------- 25.7/100.2 MB 825.4 kB/s eta 0:01:31
   ---------- ---------------------------- 26.5/100.2 MB 839.3 kB/s eta 0:01:28
   ---------- ---------------------------- 26.7/100.2 MB 844.1 kB/s eta 0:01:28
   ---------- ---------------------------- 27.3/100.2 MB 900.6 kB/s eta 0:01:22
   ---------- ---------------------------- 27.5/100.2 MB 905.4 kB/s eta 0:01:21
   ---------- ---------------------------- 28.0/100.2 MB 914.3 kB/s eta 0:01:19
   ----------- --------------------------- 28.6/100.2 MB 923.5 kB/s eta 0:01:18
   ----------- --------------------------- 28.8/100.2 MB 927.6 kB/s eta 0:01:17
   ----------- --------------------------- 29.4/100.2 MB 936.0 kB/s eta 0:01:16
   ----------- --------------------------- 29.6/100.2 MB 941.0 kB/s eta 0:01:16
   ----------- --------------------------- 30.1/100.2 MB 949.2 kB/s eta 0:01:14
   ----------- --------------------------- 30.4/100.2 MB 953.0 kB/s eta 0:01:14
   ------------ -------------------------- 30.9/100.2 MB 969.8 kB/s eta 0:01:12
   ------------ -------------------------- 31.2/100.2 MB 974.0 kB/s eta 0:01:11
   ------------ -------------------------- 31.7/100.2 MB 985.9 kB/s eta 0:01:10
   ------------ --------------------------- 32.2/100.2 MB 1.0 MB/s eta 0:01:08
   ------------ --------------------------- 32.5/100.2 MB 1.0 MB/s eta 0:01:08
   ------------- -------------------------- 33.0/100.2 MB 1.0 MB/s eta 0:01:07
   ------------- -------------------------- 33.3/100.2 MB 1.0 MB/s eta 0:01:06
   ------------- -------------------------- 33.8/100.2 MB 1.0 MB/s eta 0:01:05
   ------------- -------------------------- 34.3/100.2 MB 1.0 MB/s eta 0:01:04
   ------------- -------------------------- 34.6/100.2 MB 1.1 MB/s eta 0:01:02
   -------------- ------------------------- 35.1/100.2 MB 1.1 MB/s eta 0:01:01
   -------------- ------------------------- 35.4/100.2 MB 1.1 MB/s eta 0:01:01
   -------------- ------------------------- 35.9/100.2 MB 1.1 MB/s eta 0:01:00
   -------------- ------------------------- 36.2/100.2 MB 1.1 MB/s eta 0:00:57
   -------------- ------------------------- 36.7/100.2 MB 1.1 MB/s eta 0:00:56
   -------------- ------------------------- 37.2/100.2 MB 1.2 MB/s eta 0:00:55
   -------------- ------------------------- 37.5/100.2 MB 1.2 MB/s eta 0:00:55
   --------------- ------------------------ 38.0/100.2 MB 1.2 MB/s eta 0:00:54
   --------------- ------------------------ 38.3/100.2 MB 1.2 MB/s eta 0:00:54
   --------------- ------------------------ 38.8/100.2 MB 1.2 MB/s eta 0:00:53
   --------------- ------------------------ 39.1/100.2 MB 1.2 MB/s eta 0:00:52
   --------------- ------------------------ 39.6/100.2 MB 1.2 MB/s eta 0:00:51
   --------------- ------------------------ 39.8/100.2 MB 1.2 MB/s eta 0:00:51
   ---------------- ----------------------- 40.4/100.2 MB 1.2 MB/s eta 0:00:50
   ---------------- ----------------------- 40.9/100.2 MB 1.2 MB/s eta 0:00:50
   ---------------- ----------------------- 41.2/100.2 MB 1.2 MB/s eta 0:00:49
   ---------------- ----------------------- 41.7/100.2 MB 1.2 MB/s eta 0:00:48
   ---------------- ----------------------- 41.9/100.2 MB 1.2 MB/s eta 0:00:48
   ---------------- ----------------------- 42.5/100.2 MB 1.2 MB/s eta 0:00:47
   ----------------- ---------------------- 42.7/100.2 MB 1.2 MB/s eta 0:00:47
   ----------------- ---------------------- 43.3/100.2 MB 1.3 MB/s eta 0:00:46
   ----------------- ---------------------- 43.5/100.2 MB 1.3 MB/s eta 0:00:46
   ----------------- ---------------------- 44.0/100.2 MB 1.3 MB/s eta 0:00:45
   ----------------- ---------------------- 44.3/100.2 MB 1.3 MB/s eta 0:00:44
   ----------------- ---------------------- 44.8/100.2 MB 1.3 MB/s eta 0:00:44
   ----------------- ---------------------- 45.1/100.2 MB 1.3 MB/s eta 0:00:43
   ------------------ --------------------- 45.6/100.2 MB 1.3 MB/s eta 0:00:43
   ------------------ --------------------- 46.1/100.2 MB 1.3 MB/s eta 0:00:42
   ------------------ --------------------- 46.4/100.2 MB 1.3 MB/s eta 0:00:42
   ------------------ --------------------- 46.9/100.2 MB 1.3 MB/s eta 0:00:41
   ------------------ --------------------- 47.2/100.2 MB 1.3 MB/s eta 0:00:41

In [12]:
pip install xgboost

Collecting xgboostNote: you may need to restart the kernel to use updated packages.

  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\admin\appdata\roaming\python\python312\site-packages (from xgboost) (2.1.0)
Requirement already satisfied: scipy in e:\college material\python\venv\lib\site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 62.4 kB/s eta 0:27:02
   ---------------------------------------- 0.5/101.7 MB 62.4 kB/s eta 0:27:02
   ---------------------------------------- 0.5/101.7 MB 62.4 kB/s eta 0:27:02
   ---------------------------------------- 0.5/101.7 MB 62.4 kB/s eta 0:27:02
   ---------------------------------------- 0.5/101.7 MB 62.4 kB/s eta 0:27:02
   ---------------------------------------- 0.8/101.7 MB 94.8 kB/s eta 0:17:45
   ---------------------------------------- 0.8/101.7 MB 94.8 kB/s eta 0:17:45
   ---------------------------------------- 0.8/101.7 MB 94.8 kB/s eta 0:17:45
   ---------------------------------------- 1.0/101.7 MB 128.7 kB/s eta 0:13:02
   ---------------------------------------- 1.0/101.7 MB 128.7 kB/s eta 0:13:02
    --------------------------------------- 1.3/101.7 MB 158.7 kB/s eta 0:10:33
    --------------------------------------- 1.3/101.7 MB 158.7 kB/s eta 0:10:33
    --------------------------------------- 1.3/101.7 MB 158.7 kB/s eta 0:10:33
    --------------------------------------- 1.6/101.7 MB 181.6 kB/s eta 0:09:12
    --------------------------------------- 1.6/101.7 MB 181.6 kB/s eta 0:09:12
    --------------------------------------- 1.6/101.7 MB 181.6 kB/s eta 0:09:12
    --------------------------------------- 1.6/101.7 MB 181.6 kB/s eta 0:09:12
    --------------------------------------- 1.6/101.7 MB 181.6 kB/s eta 0:09:12
    --------------------------------------- 1.6/101.7 MB 181.6 kB/s eta 0:09:12
    --------------------------------------- 1.6/101.7 MB 181.6 kB/s eta 0:09:12
    --------------------------------------- 1.6/101.7 MB 181.6 kB/s eta 0:09:12
    --------------------------------------- 1.6/101.7 MB 181.6 kB/s eta 0:09:12
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 1.8/101.7 MB 168.1 kB/s eta 0:09:55
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.1/101.7 MB 147.9 kB/s eta 0:11:14
    --------------------------------------- 2.4/101.7 MB 133.7 kB/s eta 0:12:23
    --------------------------------------- 2.4/101.7 MB 133.7 kB/s eta 0:12:23
    --------------------------------------- 2.4/101.7 MB 133.7 kB/s eta 0:12:23
    --------------------------------------- 2.4/101.7 MB 133.7 kB/s eta 0:12:23
   - -------------------------------------- 2.6/101.7 MB 142.6 kB/s eta 0:11:35
   - -------------------------------------- 2.6/101.7 MB 142.6 kB/s eta 0:11:35
   - -------------------------------------- 2.6/101.7 MB 142.6 kB/s eta 0:11:35
   - -------------------------------------- 2.9/101.7 MB 152.7 kB/s eta 0:10:48
   - -------------------------------------- 2.9/101.7 MB 152.7 kB/s eta 0:10:48
   - -------------------------------------- 2.9/101.7 MB 152.7 kB/s eta 0:10:48
   - -------------------------------------- 2.9/101.7 MB 152.7 kB/s eta 0:10:48
   - -------------------------------------- 3.1/101.7 MB 158.4 kB/s eta 0:10:23
   - -------------------------------------- 3.1/101.7 MB 158.4 kB/s eta 0:10:23
   - -------------------------------------- 3.1/101.7 MB 158.4 kB/s eta 0:10:23
   - -------------------------------------- 3.1/101.7 MB 158.4 kB/s eta 0:10:23
   - -------------------------------------- 3.1/101.7 MB 158.4 kB/s eta 0:10:23
   - -------------------------------------- 3.1/101.7 MB 158.4 kB/s eta 0:10:23
   - -------------------------------------- 3.1/101.7 MB 158.4 kB/s eta 0:10:23
   - -------------------------------------- 3.1/101.7 MB 158.4 kB/s eta 0:10:23
   - -------------------------------------- 3.1/101.7 MB 158.4 kB/s eta 0:10:23
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.4/101.7 MB 154.5 kB/s eta 0:10:37
   - -------------------------------------- 3.7/101.7 MB 133.4 kB/s eta 0:12:15
   - -------------------------------------- 3.7/101.7 MB 133.4 kB/s eta 0:12:15
   - -------------------------------------- 3.7/101.7 MB 133.4 kB/s eta 0:12:15
   - -------------------------------------- 3.7/101.7 MB 133.4 kB/s eta 0:12:15
   - -------------------------------------- 3.9/101.7 MB 138.2 kB/s eta 0:11:48
   - -------------------------------------- 3.9/101.7 MB 138.2 kB/s eta 0:11:48
   - -------------------------------------- 3.9/101.7 MB 138.2 kB/s eta 0:11:48
   - -------------------------------------- 3.9/101.7 MB 138.2 kB/s eta 0:11:48
   - -------------------------------------- 3.9/101.7 MB 138.2 kB/s eta 0:11:48
   - -------------------------------------- 4.2/101.7 MB 141.4 kB/s eta 0:11:30
   - -------------------------------------- 4.2/101.7 MB 141.4 kB/s eta 0:11:30
   - -------------------------------------- 4.2/101.7 MB 141.4 kB/s eta 0:11:30
   - -------------------------------------- 4.2/101.7 MB 141.4 kB/s eta 0:11:30
   - -------------------------------------- 4.2/101.7 MB 141.4 kB/s eta 0:11:30
   - -------------------------------------- 4.2/101.7 MB 141.4 kB/s eta 0:11:30
   - -------------------------------------- 4.2/101.7 MB 141.4 kB/s eta 0:11:30
   - -------------------------------------- 4.2/101.7 MB 141.4 kB/s eta 0:11:30
   - -------------------------------------- 4.2/101.7 MB 141.4 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.5/101.7 MB 141.0 kB/s eta 0:11:30
   - -------------------------------------- 4.7/101.7 MB 143.4 kB/s eta 0:11:17
   - -------------------------------------- 4.7/101.7 MB 143.4 kB/s eta 0:11:17
   - -------------------------------------- 4.7/101.7 MB 143.4 kB/s eta 0:11:17
   - -------------------------------------- 4.7/101.7 MB 143.4 kB/s eta 0:11:17
   - -------------------------------------- 4.7/101.7 MB 143.4 kB/s eta 0:11:17
   - -------------------------------------- 4.7/101.7 MB 143.4 kB/s eta 0:11:17
   - -------------------------------------- 4.7/101.7 MB 143.4 kB/s eta 0:11:17
   - -------------------------------------- 4.7/101.7 MB 143.4 kB/s eta 0:11:17
   - -------------------------------------- 5.0/101.7 MB 141.2 kB/s eta 0:11:25
   - -------------------------------------- 5.0/101.7 MB 141.2 kB/s eta 0:11:25
   - -------------------------------------- 5.0/101.7 MB 141.2 kB/s eta 0:11:25
   -- ------------------------------------- 5.2/101.7 MB 141.3 kB/s eta 0:11:23
   -- ------------------------------------- 5.2/101.7 MB 141.3 kB/s eta 0:11:23
   -- ------------------------------------- 5.5/101.7 MB 140.8 kB/s eta 0:11:24
   -- ------------------------------------- 5.5/101.7 MB 140.8 kB/s eta 0:11:24
   -- ------------------------------------- 5.5/101.7 MB 140.8 kB/s eta 0:11:24
   -- ------------------------------------- 5.5/101.7 MB 140.8 kB/s eta 0:11:24
   -- ------------------------------------- 5.5/101.7 MB 140.8 kB/s eta 0:11:24
   -- ------------------------------------- 5.8/101.7 MB 139.1 kB/s eta 0:11:30
   -- ------------------------------------- 5.8/101.7 MB 139.1 kB/s eta 0:11:30
   -- ------------------------------------- 5.8/101.7 MB 139.1 kB/s eta 0:11:30
   -- ------------------------------------- 5.8/101.7 MB 139.1 kB/s eta 0:11:30
   -- ------------------------------------- 5.8/101.7 MB 139.1 kB/s eta 0:11:30
   -- ------------------------------------- 5.8/101.7 MB 139.1 kB/s eta 0:11:30
   -- ------------------------------------- 5.8/101.7 MB 139.1 kB/s eta 0:11:30
   -- ------------------------------------- 5.8/101.7 MB 139.1 kB/s eta 0:11:30
   -- ------------------------------------- 5.8/101.7 MB 139.1 kB/s eta 0:11:30
   -- ------------------------------------- 5.8/101.7 MB 139.1 kB/s eta 0:11:30
   -- ------------------------------------- 5.8/101.7 MB 139.1 kB/s eta 0:11:30
   -- ------------------------------------- 5.8/101.7 MB 139.1 kB/s eta 0:11:30
   -- ------------------------------------- 6.0/101.7 MB 141.5 kB/s eta 0:11:16
   -- ------------------------------------- 6.0/101.7 MB 141.5 kB/s eta 0:11:16
   -- ------------------------------------- 6.0/101.7 MB 141.5 kB/s eta 0:11:16
   -- ------------------------------------- 6.0/101.7 MB 141.5 kB/s eta 0:11:16
   -- ------------------------------------- 6.0/101.7 MB 141.5 kB/s eta 0:11:16
   -- ------------------------------------- 6.0/101.7 MB 141.5 kB/s eta 0:11:16
   -- ------------------------------------- 6.0/101.7 MB 141.5 kB/s eta 0:11:16
   -- ------------------------------------- 6.0/101.7 MB 141.5 kB/s eta 0:11:16
   -- ------------------------------------- 6.0/101.7 MB 141.5 kB/s eta 0:11:16
   -- ------------------------------------- 6.0/101.7 MB 141.5 kB/s eta 0:11:16
   -- ------------------------------------- 6.0/101.7 MB 141.5 kB/s eta 0:11:16
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.3/101.7 MB 146.1 kB/s eta 0:10:53
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.6/101.7 MB 132.3 kB/s eta 0:11:59
   -- ------------------------------------- 6.8/101.7 MB 124.4 kB/s eta 0:12:43
   -- ------------------------------------- 6.8/101.7 MB 124.4 kB/s eta 0:12:43
   -- ------------------------------------- 7.1/101.7 MB 131.9 kB/s eta 0:11:58
   -- ------------------------------------- 7.1/101.7 MB 131.9 kB/s eta 0:11:58
   -- ------------------------------------- 7.1/101.7 MB 131.9 kB/s eta 0:11:58
   -- ------------------------------------- 7.1/101.7 MB 131.9 kB/s eta 0:11:58
   -- ------------------------------------- 7.1/101.7 MB 131.9 kB/s eta 0:11:58
   -- ------------------------------------- 7.3/101.7 MB 135.5 kB/s eta 0:11:37
   -- ------------------------------------- 7.3/101.7 MB 135.5 kB/s eta 0:11:37
   -- ------------------------------------- 7.3/101.7 MB 135.5 kB/s eta 0:11:37
   -- ------------------------------------- 7.3/101.7 MB 135.5 kB/s eta 0:11:37
   -- ------------------------------------- 7.3/101.7 MB 135.5 kB/s eta 0:11:37
   -- ------------------------------------- 7.3/101.7 MB 135.5 kB/s eta 0:11:37
   -- ------------------------------------- 7.3/101.7 MB 135.5 kB/s eta 0:11:37
   -- ------------------------------------- 7.3/101.7 MB 135.5 kB/s eta 0:11:37

In [15]:
df = pd.read_csv('stud.csv')

In [16]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [17]:
X = df.drop(columns=['math_score'],axis=1)

In [18]:
X.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [19]:
print("Categories in 'gender' variable:     ",end=" " )
print(df['gender'].unique())

print("Categories in 'race_ethnicity' variable:  ",end=" ")
print(df['race_ethnicity'].unique())

print("Categories in'parental level of education' variable:",end=" " )
print(df['parental_level_of_education'].unique())

print("Categories in 'lunch' variable:     ",end=" " )
print(df['lunch'].unique())

print("Categories in 'test preparation course' variable:     ",end=" " )
print(df['test_preparation_course'].unique())

Categories in 'gender' variable:      ['female' 'male']
Categories in 'race_ethnicity' variable:   ['group B' 'group C' 'group A' 'group D' 'group E']
Categories in'parental level of education' variable: ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
Categories in 'lunch' variable:      ['standard' 'free/reduced']
Categories in 'test preparation course' variable:      ['none' 'completed']

In [20]:
y = df['math_score']

In [21]:
y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64